version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "disabled"
  allow:
    - dependency-type: "all"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "disabled"
  allow:
    - dependency-type: "all"
