require 'nokogiri'
require 'open-uri'

module Vds
  class CalendarScraper

    def call
      race_urls.each { |url| scrape_race_info(url) }
    end

    def scrape_race_info(url)
      begin
        doc = Nokogiri::HTML(URI.open(url))
        start_date = doc.css(".infolist.fs13 li:first-child div")[1]&.text&.strip
        stages_text = doc.at_css(".sub .blue" )&.text&.strip
        stages = stages_text&.match(/(\d+) stages?/i)&.captures&.first
        puts "#{url},#{start_date},#{stages || 'N/A'}"
      rescue StandardError => e
        puts "Error scraping #{url}: #{e.message}"
      end
    end

    def race_urls
      ['https://www.procyclingstats.com/race/uae-tour/2025',
      'https://www.procyclingstats.com/race/gran-camino/2025',
      'https://www.procyclingstats.com/race/faun-ardeche-classic/2025',
      'https://www.procyclingstats.com/race/omloop-het-nieuwsblad/2025',
      'https://www.procyclingstats.com/race/kuurne-brussel-kuurne/2025',
      'https://www.procyclingstats.com/race/la-drome-classic/2025',
      'https://www.procyclingstats.com/race/gp-samyn/2025',
      'https://www.procyclingstats.com/race/trofeo-laigueglia/2025',
      'https://www.procyclingstats.com/race/strade-bianche/2025',
      'https://www.procyclingstats.com/race/grand-prix-criquielion/2025',
      'https://www.procyclingstats.com/race/paris-nice/2025',
      'https://www.procyclingstats.com/race/grote-prijs-jean-pierre-monsere/2025',
      'https://www.procyclingstats.com/race/tirreno-adriatico/2025',
      'https://www.procyclingstats.com/race/milano-torino/2025',
      'https://www.procyclingstats.com/race/nokere-koers/2025',
      'https://www.procyclingstats.com/race/gp-de-denain/2025',
      'https://www.procyclingstats.com/race/bredene-koksijde-classic/2025',
      'https://www.procyclingstats.com/race/milano-sanremo/2025',
      'https://www.procyclingstats.com/race/classic-loire-atlantique/2025',
      'https://www.procyclingstats.com/race/cholet-pays-de-loire/2025',
      'https://www.procyclingstats.com/race/per-sempre-alfredo/2025',
      'https://www.procyclingstats.com/race/volta-a-catalunya/2025',
      'https://www.procyclingstats.com/race/settimana-internazionale-coppi-e-bartali/2025',
      'https://www.procyclingstats.com/race/classic-brugge-de-panne/2025',
      'https://www.procyclingstats.com/race/e3-harelbeke/2025',
      'https://www.procyclingstats.com/race/gent-wevelgem/2025',
      'https://www.procyclingstats.com/race/la-roue-tourangelle/2025',
      'https://www.procyclingstats.com/race/dwars-door-vlaanderen/2025',
      'https://www.procyclingstats.com/race/paris-camembert/2025',
      'https://www.procyclingstats.com/race/route-adelie-de-vitre/2025',
      'https://www.procyclingstats.com/race/volta-nxt-classic/2025',
      'https://www.procyclingstats.com/race/gran-premio-miguel-indurain/2025',
      'https://www.procyclingstats.com/race/ronde-van-vlaanderen/2025',
      'https://www.procyclingstats.com/race/itzulia-basque-country/2025',
      'https://www.procyclingstats.com/race/region-pays-de-la-loire/2025',
      'https://www.procyclingstats.com/race/scheldeprijs/2025',
      'https://www.procyclingstats.com/race/paris-roubaix/2025',
      'https://www.procyclingstats.com/race/paris-roubaix-juniors/2025',
      'https://www.procyclingstats.com/race/giro-di-reggio-calabria/2025',
      'https://www.procyclingstats.com/race/giro-di-sicilia/2025',
      'https://www.procyclingstats.com/race/brabantse-pijl/2025',
      'https://www.procyclingstats.com/race/classic-grand-besancon-doubs/2025',
      'https://www.procyclingstats.com/race/tour-du-jura-cycliste/2025',
      'https://www.procyclingstats.com/race/amstel-gold-race/2025',
      'https://www.procyclingstats.com/race/tour-du-doubs/2025',
      'https://www.procyclingstats.com/race/tour-of-the-alps/2025',
      'https://www.procyclingstats.com/race/la-fleche-wallone/2025',
      'https://www.procyclingstats.com/race/liege-bastogne-liege/2025',
      'https://www.procyclingstats.com/race/tour-of-turkey/2025',
      'https://www.procyclingstats.com/race/giro-di-romagna/2025',
      'https://www.procyclingstats.com/race/tour-de-romandie/2025',
      'https://www.procyclingstats.com/race/vuelta-asturias/2025',
      'https://www.procyclingstats.com/race/famenne-ardenne-classic/2025',
      'https://www.procyclingstats.com/race/eschborn-frankfurt/2025',
      'https://www.procyclingstats.com/race/giro-d-italia/2025',
      'https://www.procyclingstats.com/race/gp-de-plumelec/2025',
      'https://www.procyclingstats.com/race/circuit-des-xi-villes/2025',
      'https://www.procyclingstats.com/race/tro-bro-leon/2025',
      'https://www.procyclingstats.com/race/tour-de-hongrie/2025',
      'https://www.procyclingstats.com/race/circuit-de-wallonie/2025',
      'https://www.procyclingstats.com/race/tour-du-finistere/2025',
      'https://www.procyclingstats.com/race/boucles-de-l-aulne/2025',
      'https://www.procyclingstats.com/race/4-jours-de-dunkerque/2025',
      'https://www.procyclingstats.com/race/veenendaal-veenendaal/2025',
      'https://www.procyclingstats.com/race/antwerp-port-epic/2025',
      'https://www.procyclingstats.com/race/ronde-van-limburg/2025',
      'https://www.procyclingstats.com/race/tour-of-norway/2025',
      'https://www.procyclingstats.com/race/boucles-de-la-mayenne/2025',
      'https://www.procyclingstats.com/race/tour-of-estonia/2025',
      'https://www.procyclingstats.com/race/grote-prijs-marcel-kint/2025',
      'https://www.procyclingstats.com/race/rund-um-koln/2025',
      'https://www.procyclingstats.com/race/mercan-tour-classic-alpes-maritimes/2025',
      'https://www.procyclingstats.com/race/circuit-franco-belge/2025',
      'https://www.procyclingstats.com/race/heist-op-den-berg/2025',
      'https://www.procyclingstats.com/race/dauphine/2025',
      'https://www.procyclingstats.com/race/brussels-cycling-classic/2025',
      'https://www.procyclingstats.com/race/zlm-tour/2025',
      'https://www.procyclingstats.com/race/gp-du-canton-d-argovie/2025',
      'https://www.procyclingstats.com/race/dwars-door-het-hageland/2025',
      'https://www.procyclingstats.com/race/tour-de-suisse/2025',
      'https://www.procyclingstats.com/race/tour-of-slovenia/2025',
      'https://www.procyclingstats.com/race/tour-of-belgium/2025',
      'https://www.procyclingstats.com/race/la-route-d-occitanie/2025',
      'https://www.procyclingstats.com/race/okolo-slovenska/2025',
      'https://www.procyclingstats.com/race/tour-de-france/2025',
      'https://www.procyclingstats.com/race/tour-of-austria/2025',
      'https://www.procyclingstats.com/race/sibiu-cycling-tour/2025',
      'https://www.procyclingstats.com/race/tour-of-qinghai-lake/2025',
      'https://www.procyclingstats.com/race/settimana-ciclista-lombarda/2025',
      'https://www.procyclingstats.com/race/tour-de-l-ain/2025',
      'https://www.procyclingstats.com/race/giro-del-appennino/2025',
      'https://www.procyclingstats.com/race/tour-de-wallonie/2025',
      'https://www.procyclingstats.com/race/vuelta-a-castilla-y-leon/2025',
      'https://www.procyclingstats.com/race/volta-a-portugal/2025',
      'https://www.procyclingstats.com/race/prueba-villafranca/2025',
      'https://www.procyclingstats.com/race/czech-tour/2025',
      'https://www.procyclingstats.com/race/olympic-games-itt/2025',
      'https://www.procyclingstats.com/race/olympic-games/2025',
      'https://www.procyclingstats.com/race/arctic-race-of-norway/2025',
      'https://www.procyclingstats.com/race/vuelta-a-burgos/2025',
      'https://www.procyclingstats.com/race/san-sebastian/2025',
      'https://www.procyclingstats.com/race/la-poly-normande/2025',
      'https://www.procyclingstats.com/race/circuito-de-getxo/2025',
      'https://www.procyclingstats.com/race/tour-de-pologne/2025',
      'https://www.procyclingstats.com/race/tour-du-limousin/2025',
      'https://www.procyclingstats.com/race/tour-of-denmark/2025',
      'https://www.procyclingstats.com/race/gp-jef-scherens/2025',
      'https://www.procyclingstats.com/race/vuelta-a-espana/2025',
      'https://www.procyclingstats.com/race/gp-stad-zottegem/2025',
      'https://www.procyclingstats.com/race/tour-du-poitou-charentes-et-de-la-vienne/2025',
      'https://www.procyclingstats.com/race/deutschland-tour/2025',
      'https://www.procyclingstats.com/race/druivenkoers-overijse/2025',
      'https://www.procyclingstats.com/race/bretagne-classic/2025',
      'https://www.procyclingstats.com/race/renewi-tour/2025',
      'https://www.procyclingstats.com/race/muur-classic-geraardsbergen/2025',
      'https://www.procyclingstats.com/race/maryland-cycling-classic/2025',
      'https://www.procyclingstats.com/race/tour-of-britain/2025',
      'https://www.procyclingstats.com/race/cyclassics-hamburg/2025',
      'https://www.procyclingstats.com/race/gp-industria-artigianato/2025',
      'https://www.procyclingstats.com/race/gp-de-fourmies/2025',
      'https://www.procyclingstats.com/race/uec-road-european-championships-itt/2025',
      'https://www.procyclingstats.com/race/giro-di-toscana/2025',
      'https://www.procyclingstats.com/race/gp-citta-di-peccioli/2025',
      'https://www.procyclingstats.com/race/gp-quebec/2025',
      'https://www.procyclingstats.com/race/memorial-marco-pantani/2025',
      'https://www.procyclingstats.com/race/uec-road-european-championships/2025',
      'https://www.procyclingstats.com/race/gp-montreal/2025',
      'https://www.procyclingstats.com/race/gp-d-isbergues/2025',
      'https://www.procyclingstats.com/race/trofeo-matteotti/2025',
      'https://www.procyclingstats.com/race/grisette-grand-prix-de-wallonie/2025',
      'https://www.procyclingstats.com/race/tour-de-luxembourg/2025',
      'https://www.procyclingstats.com/race/adriatica-ionica-race/2025',
      'https://www.procyclingstats.com/race/kampioenschap-van-vlaanderen/2025',
      'https://www.procyclingstats.com/race/gp-impanis-van-petegem/2025',
      'https://www.procyclingstats.com/race/world-championship-itt/2025',
      'https://www.procyclingstats.com/race/paris-chauny-classique/2025',
      'https://www.procyclingstats.com/race/gooikse-pijl/2025',
      'https://www.procyclingstats.com/race/world-championships-itt-u23/2025',
      'https://www.procyclingstats.com/race/omloop-van-het-houtland-lichtervelde/2025',
      'https://www.procyclingstats.com/race/world-championships-mixed-relay-ttt/2025',
      'https://www.procyclingstats.com/race/tour-of-istanbul/2025',
      'https://www.procyclingstats.com/race/world-championships-u23/2025',
      'https://www.procyclingstats.com/race/world-championship/2025',
      'https://www.procyclingstats.com/race/tour-de-langkawi/2025',
      'https://www.procyclingstats.com/race/memorial-frank-vandenbroucke/2025',
      'https://www.procyclingstats.com/race/tour-of-croatia/2025',
      'https://www.procyclingstats.com/race/elfsteden-race/2025',
      'https://www.procyclingstats.com/race/munsterland-giro/2025',
      'https://www.procyclingstats.com/race/paris-bourges/2025',
      'https://www.procyclingstats.com/race/coppa-agostoni/2025',
      'https://www.procyclingstats.com/race/coppa-bernocchi/2025',
      'https://www.procyclingstats.com/race/tre-valli-varesine/2025',
      'https://www.procyclingstats.com/race/gran-piemonte/2025',
      'https://www.procyclingstats.com/race/tour-of-taihu-lake/2025',
      'https://www.procyclingstats.com/race/il-lombardia/2025',
      'https://www.procyclingstats.com/race/chrono-des-nations/2025',
      'https://www.procyclingstats.com/race/trofeo-baracchi/2025',
      'https://www.procyclingstats.com/race/tour-of-guangxi/2025',
      'https://www.procyclingstats.com/race/giro-del-veneto/2025',
      'https://www.procyclingstats.com/race/veneto-classic/2025',
      'https://www.procyclingstats.com/race/japan-cup/2025']
    end
  end
end